language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
 - pyflakes instabot tests
 - pep8 --ignore=E223,E501 instabot tests
 - py.test

branches:
  only:
    - master
